### ISSUE TITLE
刚clone的项目 运行不起来

### ISSUE THREAD

**Issue by HeWenKe** [Geek-James/ddBuy#56]
![image](https://user-images.githubusercontent.com/12146992/75304968-b2147f00-587f-11ea-85ae-df0042e77dba.png)

**Comment by Geek-James** [comment]
看起来是你的npm的问题 你可以重新安装下你的node环境并重新安装vue-cli.
npm install -g @vue/cli

**Comment by HeWenKe** [comment]
node 是上周安装的，其他项目可以起来。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "极客-James"<notifications@github.com&gt;; 
发送时间: 2020年2月26日(星期三) 上午10:11
收件人: "Geek-James/ddBuy"<ddBuy@noreply.github.com&gt;; 
抄送: "雪域之巅"<1027186808@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Geek-James/ddBuy] 刚clone的项目 运行不起来 (#56)




看起来是你的npm的问题 你可以重新安装下你的node环境并重新安装vue-cli.
 npm install -g @vue/cli

**Comment by HeWenKe** [comment]
你好，可以加一下您的qq吗&nbsp; ，最近再搭建商城，第一次做这个，想请教一下您，非常感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "极客-James"<notifications@github.com&gt;; 
发送时间: 2020年2月26日(星期三) 上午10:11
收件人: "Geek-James/ddBuy"<ddBuy@noreply.github.com&gt;; 
抄送: "雪域之巅"<1027186808@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Geek-James/ddBuy] 刚clone的项目 运行不起来 (#56)




看起来是你的npm的问题 你可以重新安装下你的node环境并重新安装vue-cli.
 npm install -g @vue/cli

**Comment by Geek-James** [comment]
环境问题,项目本身没有问题.

**Comment by HeWenKe** [comment]
没事，我学习学习，把项目运行起来，目前的这个项目和你的这个相似度太高，感谢大佬。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "极客-James"<notifications@github.com&gt;; 
发送时间: 2020年2月26日(星期三) 上午10:57
收件人: "Geek-James/ddBuy"<ddBuy@noreply.github.com&gt;; 
抄送: "雪域之巅"<1027186808@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Geek-James/ddBuy] 刚clone的项目 运行不起来 (#56)




环境问题,项目本身没有问题.

**Comment by Geek-James** [comment]
好的 加油💪 点个stat支持下~~

**Comment by HeWenKe** [comment]
你这个是适配 能简单说一下吗

**Comment by Geek-James** [comment]
样式是Flex 布局
字体是rem适配
UI用的是vant,很多都是适配好的,开箱即用.

**Comment by HeWenKe** [comment]
能加一下你的qq 吗，请教几个问题

**Comment by Geek-James** [comment]
可以扫描主页微信哦!
