### ISSUE TITLE
建议：菜单增加可滑动功能

### ISSUE THREAD

**Issue by Sunshine-Zuo** [Geek-James/ddBuy#7]
“吃什么”上方的菜单要是支持左右滑动会更好

**Comment by Geek-James** [comment]
> “吃什么”上方的菜单要是支持左右滑动会更好

eeeee 横向是可以滑动的呢.

**Comment by Sunshine-Zuo** [comment]
这个，，，我电脑Chrome浏览器移动端模式不能滑，刚用手机试了下可以，可能是浏览器问题吧
